# Auto-generated by setup_cython.py
from setuptools import setup, Extension
from Cython.Build import cythonize
import sys, os
os.chdir(r"O:\World of Warcraft\_retail_\Interface\AddOns\Cyber_Deck\Arasaka\class")
sys.argv = ['setup.py', 'build_ext', '--inplace']
setup(
    ext_modules=cythonize(
        [Extension("warlock_logic", [r"O:\World of Warcraft\_retail_\Interface\AddOns\Cyber_Deck\Arasaka\class\warlock_logic.py"])],
        language_level=3,
        quiet=True,
    ),
)
